# Generated by Django 4.2.16 on 2026-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_affirmation_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
