from django.urls import path
from . import views

urlpatterns = [
    path("products/", views.ProductsView.as_view(), name="products"),
    path("products/create/", views.ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/update/", views.ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", views.ProductDeleteView.as_view(), name="product-delete"),
    path("product-images/<int:pk>/", views.ProductImageDeleteView.as_view(), name="product-image-delete"),
    path("blog-posts/", views.BlogPostsView.as_view(), name="blog-posts"),
    path("blog-posts/create/", views.BlogPostCreateView.as_view(), name="blog-post-create"),
    path("blog-posts/<int:pk>/update/", views.BlogPostUpdateView.as_view(), name="blog-post-update"),
    path("blog-posts/<int:pk>/delete/", views.BlogPostDeleteView.as_view(), name="blog-post-delete"),
    path("affirmations/", views.AffirmationsView.as_view(), name="affirmations"),
    path("affirmations/create/", views.AffirmationCreateView.as_view(), name="affirmation-create"),
    path("affirmations/<int:pk>/update/", views.AffirmationUpdateView.as_view(), name="affirmation-update"),
    path("affirmations/<int:pk>/delete/", views.AffirmationDeleteView.as_view(), name="affirmation-delete"),
    path("place-order/", views.PlaceOrderView.as_view(), name="place-order"),
    path("reseller-sales/", views.ResellerSalesView.as_view(), name="reseller-sales"),
    path("calendar/", views.CalendarView.as_view(), name="calendar"),
    path("reels/", views.ReelsView.as_view(), name="reels"),
    path("reels/create/", views.ReelCreateView.as_view(), name="reel-create"),
    path("reels/admin-list/", views.ReelAdminListView.as_view(), name="reel-admin-list"),
    path("reels/<int:pk>/delete/", views.ReelDeleteView.as_view(), name="reel-delete"),
    path("reels/<int:pk>/like/", views.ReelLikeView.as_view(), name="reel-like"),
    path("reels/<int:pk>/comments/", views.ReelCommentsView.as_view(), name="reel-comments"),
    path("track-pageview/", views.TrackPageViewView.as_view(), name="track-pageview"),
    path("track-pageview/<int:pk>/duration/", views.TrackPageDurationView.as_view(), name="track-pageview-duration"),
    path("track-product-click/", views.TrackProductClickView.as_view(), name="track-product-click"),
    path("analytics/", views.AnalyticsView.as_view(), name="analytics"),
    path("admin-orders/", views.AdminOrdersListView.as_view(), name="admin-orders"),
    path("admin-orders/<int:pk>/status/", views.AdminOrderStatusView.as_view(), name="admin-order-status"),
    path("track-order/", views.TrackOrderView.as_view(), name="track-order"),
    path("my-orders/", views.MyOrdersView.as_view(), name="my-orders"),
]
