# Generated by Django 4.2.16 on 2026-06-06 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reseller_code', models.CharField(max_length=20, unique=True)),
                ('reseller_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('reseller_type', models.CharField(choices=[('retail', 'Retail Reseller'), ('influencer', 'Influencer Reseller')], default='retail', max_length=20)),
                ('referral_link', models.URLField(max_length=500)),
                ('qr_image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='address_proofs/')),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('social_handle', models.CharField(blank=True, max_length=200)),
                ('follower_count', models.CharField(blank=True, max_length=50)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('period', models.CharField(max_length=50)),
                ('dates', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='resellers.reseller')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='resellers.reseller')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
