# Generated by Django 4.2.16 on 2026-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0002_resellerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
