# Generated by Django 4.2.16 on 2026-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0003_reseller_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerpayout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resellerpayout',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AddField(
            model_name='resellerpayout',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resellerpayout',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payout_proofs/'),
        ),
        migrations.AlterField(
            model_name='resellerpayout',
            name='period',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
