# Generated by Django 4.2.16 on 2026-07-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0004_payout_payment_fields'),
        ('resellers', '0004_resellerpayout_notes_resellerpayout_payment_mode_and_more'),
    ]

    operations = [
    ]
